[package]
name = "asn-parser"
version = "0.1.0"
edition = "2021"
authors = ["Manu Gupta"]
description = "A CLI tool to get ASN (Autonomous System Number) from IP addresses"
license = "MIT"
readme = "README.md"
repository = "https://github.com/manugupt1/asn-parser-rs"

[dependencies]
